In [1]:
import pandas as pd

In [2]:
filename = 'final1.csv'
data = pd.read_csv(filename)
data.head()

col         Class            Clip  Label
0    0           Cow  4-213915-C.ogg     14
1    1          Rain  3-157149-A.ogg     37
2    2  Church bells   3-98869-A.ogg      9
3    3   Can opening  4-264453-A.ogg      4
4    4           Hen  4-234879-A.ogg     30

In [3]:
data.drop('col',axis=1,inplace = True)
data.head()

Class            Clip  Label
0           Cow  4-213915-C.ogg     14
1          Rain  3-157149-A.ogg     37
2  Church bells   3-98869-A.ogg      9
3   Can opening  4-264453-A.ogg      4
4           Hen  4-234879-A.ogg     30

In [4]:
#removed = original.replace("M", "")
audio_list = []
for name in data.Clip:
    #print(name)
    new_name = name.replace(".ogg","")
    #print(new_name)
    audio_list.append(new_name)
    
data["Clip"]=pd.DataFrame(audio_list)
data.head()

Class        Clip  Label
0           Cow  4-213915-C     14
1          Rain  3-157149-A     37
2  Church bells   3-98869-A      9
3   Can opening  4-264453-A      4
4           Hen  4-234879-A     30

In [5]:
import os

path = '/Users/niki/Documents/255_final_project/ESC-50-master/audio/'
audio_files = []

for filename in os.listdir(path):
    audio_files.append(filename)
#audio_files


In [7]:
keyboard = []
# count=0
listy=[]
for name in audio_files:
#     count=count+1
    for i,j in enumerate(data['Clip']):
        if j in name:
            keyboard.append(name)
            listy.append(data['Label'][i])
            break
    

In [8]:
len(keyboard)

2000

In [9]:
len(listy)

2000

In [10]:
# mynew1=pd.DataFrame()
audio_data=pd.DataFrame({'Clip':keyboard})
# df = pd.DataFrame({'col':L})

In [11]:
audio_data['target1']=pd.DataFrame(listy)

In [12]:
audio_data.head()

Clip  target1
0  1-104089-A-22.wav       10
1  3-246513-B-16.wav       50
2    1-96950-B-9.wav       17
3  2-105270-A-47.wav        1
4   4-90014-B-42.wav       41

In [351]:
audio_data.to_csv('255audio_1200.csv')

In [391]:
d4 = pd.DataFrame()

for i in range(1,len(audio_data)):
    x1 =path + str(audio_data['Clip'][i])
    y1, sr1 = librosa.load(x1)
    f3=librosa.feature.zero_crossing_rate(y1, frame_length=2048, hop_length=512, center=True)
    log_f3 = pd.DataFrame(librosa.power_to_db(f3, ref=np.max))
    d4=pd.concat([d4,log_f3],axis=0)

In [398]:
labels = labels[0:1999]
len(labels)

1999

In [399]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(d4,labels,test_size=0.20)

In [400]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [401]:
prediction = neigh.predict(X_test)

In [402]:
from sklearn.metrics import accuracy_score
print(accuracy_score(prediction, y_test))

0.0175


In [352]:
from __future__ import print_function
import pandas as pd
import numpy as np

# matplotlib for displaying the output
import matplotlib.pyplot as plt
import matplotlib.style as ms
ms.use('seaborn-muted')
%matplotlib inline

# and IPython.display for audio output
from IPython.display import Audio
# Librosa for audio
import librosa
# And the display module for visualization
import librosa.display

In [353]:
audio_data.shape

(2000, 9)

In [354]:
trial=pd.DataFrame(audio_data.iloc[0])

In [355]:
trial=trial.T

In [356]:
trial=trial.drop("Clip", axis=1)

In [357]:
from sklearn.metrics.pairwise import chi2_kernel
X=audio_data.drop("Clip", axis=1)

In [358]:
trial=trial.drop("target1", axis=1)
X=X.drop("target1", axis=1)

In [359]:
y=audio_data["target1"]

In [360]:
from sklearn.neighbors import NearestNeighbors
X=np.array(X.replace(np.nan,0))

In [361]:
X

array([[  3.98689946e-02,   2.10388765e-01,  -9.54041206e-03, ...,
          5.68817000e-04,   4.87663899e-01,   5.73520159e-01],
       [  1.99304288e-02,   1.02069587e-01,  -9.54785482e-03, ...,
          5.18822000e-03,   4.75759478e-01,   5.43975251e-01],
       [  8.41687073e-04,   2.46872008e-02,  -9.55317187e-03, ...,
          5.00841000e-04,   5.12985677e-01,   8.25994199e-01],
       ..., 
       [  1.49159880e-02,   1.26505151e-01,  -9.54617582e-03, ...,
          1.26218000e-01,   8.90412334e-01,   5.72459536e-01],
       [  4.80886512e-03,   3.62361930e-02,  -9.55237833e-03, ...,
          8.35759000e-02,   5.88407817e-01,   6.62614258e-01],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

In [383]:
nbrs = NearestNeighbors(n_neighbors=1, algorithm='ball_tree').fit(X)

In [384]:
distances, indices = nbrs.kneighbors(X)
distances

array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]])

In [385]:
indices

array([[   0],
       [   1],
       [   2],
       ..., 
       [1997],
       [1998],
       [1999]])

In [388]:
z=audio_data['target1'][0]

In [389]:
for i,y in enumerate(data["Label"]):
    if y == z:
        class1=data["Class"][i]
        
print(class1)

Clapping


In [403]:
from email.MIMEMultipart import MIMEMultipart
from email.MIMEText import MIMEText
fromaddr = "dm.cmpe255@gmail.com"
toaddr = "nikitasngpt492@gmail.com"
msg = MIMEMultipart()
msg['From'] = fromaddr
msg['To'] = toaddr
msg['Subject'] = "Alert"
body = "Found the following sound near you: " + class1 + "Take neccessary precautions"
msg.attach(MIMEText(body, 'plain'))
import smtplib
server = smtplib.SMTP('smtp.gmail.com', 587)
server.ehlo()
server.starttls()
server.ehlo()
server.login("dm.cmpe255@gmail.com", "Cmpe_255")
text = msg.as_string()
server.sendmail(fromaddr, toaddr, text)

ModuleNotFoundError: No module named 'email.MIMEMultipart'

In [345]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20)

In [346]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [347]:
print(neigh.predict(X_test))

[ 9 11 12  4  1  9 13 18  9  7 32 10  7 12 27 17  8  9  7 25  1  5 17 12 21
  6  1  8  4  4 28  6  3  4  3 37  6 17 21  7 14 13  1 11  8 21 12 13  2 10
 29 21 17  4  8 21 23  6  8 12  5  9 14 21 10 19 10  9  3 10  4  5  4  1  9
  8 23 13 17 20  2  4 16 23  9  2 19 28 14  5 11 28 17  1  1 12  1 20 29  2
 16 38  3  4 14  6  6 30  9 12 10  1 36  5  3 11  1 12  5 30 16  9 20  2 16
  6 34  8 27 49 41 13  3  4 10  4  9 16 16 10 10  2 21  4  3 27 36  2 19 38
 14 11 23  2  1 25  1 11  6  7 17 11 15  5  1  9 15 31  4 18  1 13  2  2 28
 17  1 24 22 12  1 15 10 46  5 11 29  4 11 14 14 12  3  7  3 23  5  6  1 18
 10 13 11 19 13  6  4 14  1  8  7  4 15 11  5 14 39 30  6 25  7 17  9  1 10
  7  2 16 17  9 11 11 24  6  8 18 14 21  7 23 37 17 10 17  9  7 14  3 23  9
 12  2  1 15 29 35 21 41  2  1  6  4 26 16 33  7  4  2  6 12  9 18 21  7 48
 17 38 17 19 14 14 15  7 16 49  9  8  4 27 11 10 13 13  5 24  4 29  2 19 17
 39  2 17  7  5  9 22  4  4 24  3 12  3  8  7 11  2  8  6  7  6 15  8 23  4
 16  2  5  7

In [348]:
predicted=neigh.predict(X_test)

In [349]:
from sklearn.metrics import precision_recall_fscore_support
p,r,f,s = precision_recall_fscore_support(predicted, y_test)

/Applications/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [350]:
from sklearn.metrics import accuracy_score
print(accuracy_score(predicted, y_test))

0.365


# our logic

In [15]:
# Compute a mel-scaled spectrogram.

x =path + str(audio_data['Clip'][0])
y, sr = librosa.load(x)
f8 = np.mean(librosa.feature.melspectrogram(y=y, sr=sr, S=None, n_fft=2048, hop_length=512, power=2.0))
# log_f8 = librosa.power_to_db(f8, ref=np.max)
f8

KeyError: 'audio'

In [ ]:
# Compute root-mean-square (RMS) energy for each frame, either from the audio samples y or from a spectrogram S.
f10 = np.mean(librosa.feature.rmse(y=y, S=None, frame_length=2048, hop_length=512, center=True, pad_mode='reflect'))
f10

In [ ]:
# Compute the spectral centroid.
f11 = np.mean(librosa.feature.spectral_centroid(y=y, sr=sr, S=None, n_fft=2048, hop_length=512, freq=None))
f11

In [ ]:
#Compute the tempogram: local autocorrelation of the onset strength envelope
f1 = np.mean(librosa.feature.tempogram(y, sr=sr, onset_envelope=None, hop_length=512, win_length=384, center=True, window='hann'))
f1

In [ ]:
# Computes the tonal centroid features (tonnetz), following the method of [R8787].
f3=np.mean(librosa.feature.tonnetz(y, sr=sr, chroma=None))
f3

In [ ]:

# Compute a chromagram from a waveform or power spectrogram.
f5 = np.mean(librosa.feature.chroma_stft(y=y, sr=sr, S=None, n_fft=2048, hop_length=512, tuning=None))
f5


In [ ]:
# Compute spectral flatness.
f14 = np.mean(librosa.feature.spectral_flatness(y=y, S=None, n_fft=2048, hop_length=512, amin=1e-10, power=2.0))
f14

In [ ]:
# Compute roll-off frequency
f15 = np.mean(librosa.feature.spectral_rolloff(y=y, sr=sr, S=None, n_fft=2048, hop_length=512, freq=None, roll_percent=0.85))
f15


In [16]:
mel_spect = []
for i in range(1,len(audio_data)):
    x1 = path + str(audio_data['Clip'][i])
    print(i)
    y1, sr1 = librosa.load(x1)
    f8 = np.mean(librosa.feature.melspectrogram(y=y1, sr=sr1, S=None, n_fft=2048, hop_length=512, power=2.0))
    mel_spect.append(f8)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999


In [17]:
# mel_spect

norm_mel_spect =[ ]
min_mel = min(mel_spect)
deno_mel = max(mel_spect)-min(mel_spect)
    
for x in mel_spect:
    res=(x-min_mel)/deno_mel;
    norm_mel_spect.append(res)
    

In [18]:
rmse = []
for i in range(1,len(audio_data)):
    x1 = path + str(audio_data['Clip'][i])
    print(i)
    y1, sr1 = librosa.load(x1)
    f10 = np.mean(librosa.feature.rmse(y=y1, S=None, frame_length=2048, hop_length=512, center=True, pad_mode='reflect'))
    rmse.append(f10)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999


In [19]:

norm_rmse =[ ]
min_rmse = min(rmse)
deno_rmse = max(rmse)-min(rmse)
    
for x in rmse:
    res=(x-min_rmse)/deno_rmse;
    norm_rmse.append(res)
    

In [20]:
centroid = []
for i in range(1,len(audio_data)):
    x1 = path + str(audio_data['Clip'][i])
    print(i)
    y1, sr1 = librosa.load(x1)
    f11 = np.mean(librosa.feature.spectral_centroid(y=y1, sr=sr1, S=None, n_fft=2048, hop_length=512, freq=None))
    centroid.append(f11)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999


In [21]:
norm_centroid =[ ]
min_centroid = min(centroid)
deno_centroid = max(centroid)-min(centroid)
    
for x in rmse:
    res=(x-min_centroid)/deno_centroid;
    norm_centroid.append(res)
    

In [25]:
f1 = 'roll_off.txt'

with open(f1) as fn:
    content = fn.readlines()

roll_off = [ x.strip() for x in content] 


In [29]:
for i in range(0,len(roll_off)):
    roll_off[i] = float(roll_off[i])

In [31]:
f2 = 'spectral_flatness.txt'

with open(f2) as fn:
    content = fn.readlines()

spectral_flatness = [ x.strip() for x in content] 


for i in range(0,len(spectral_flatness)):
    spectral_flatness[i] = float(spectral_flatness[i])

In [32]:
f3 = 'chromagram.txt'

with open(f3) as fn:
    content = fn.readlines()

chromagram = [ x.strip() for x in content] 


for i in range(0,len(chromagram)):
    chromagram[i] = float(chromagram[i])

In [33]:
f4 = 'tonal.txt'

with open(f4) as fn:
    content = fn.readlines()

tonal = [ x.strip() for x in content] 


for i in range(0,len(tonal)):
    tonal[i] = float(tonal[i])

In [34]:
audio_data['mel_spectogram']=pd.DataFrame(norm_mel_spect)

In [35]:
audio_data['rmse']=pd.DataFrame(norm_rmse)

In [36]:
audio_data['centroid']=pd.DataFrame(norm_centroid)

In [37]:
audio_data['roll_off']=pd.DataFrame(roll_off)

In [38]:
audio_data['spectral_flatness']=pd.DataFrame(spectral_flatness)

In [39]:
audio_data['chromagram']=pd.DataFrame(chromagram)

In [40]:
audio_data['tonal']=pd.DataFrame(tonal)

In [115]:
audio_data.head()

Clip  target1  mel_spectogram      rmse  centroid  roll_off  \
0  1-104089-A-22.wav       10        0.039869  0.210389 -0.009540  0.090430   
1  3-246513-B-16.wav       50        0.019930  0.102070 -0.009548  0.243400   
2    1-96950-B-9.wav       17        0.000842  0.024687 -0.009553  0.105542   
3  2-105270-A-47.wav        1        0.008067  0.080833 -0.009549  0.260671   
4   4-90014-B-42.wav       41        0.000214  0.004478 -0.009555  0.324043   

   spectral_flatness  chromagram     tonal  
0           0.000569    0.487664  0.573520  
1           0.005188    0.475759  0.543975  
2           0.000501    0.512986  0.825994  
3           0.002288    0.296620  0.516057  
4           0.537329    0.334689  0.618730

In [116]:
labels = audio_data['target1']

In [117]:
TRAIN = audio_data.drop('target1',axis=1)

In [118]:
TRAIN.drop('Clip',axis=1,inplace = True)

In [119]:
TRAIN = TRAIN.replace(np.nan, 0)

In [132]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(TRAIN,labels,test_size=0.30)

In [133]:
#X_test.dtypes

In [134]:
# X_test["mel_spectogram"]=round(X_test["mel_spectogram"],4)
# X_test["rmse"]=round(X_test["rmse"],4)
# X_test["centroid"]=round(X_test["centroid"],4)
# X_test["roll_off"]=round(X_test["roll_off"],4)
# X_test["spectral_flatness"]=round(X_test["spectral_flatness"],4)
# X_test["chromagram"]=round(X_test["chromagram"],4)
# X_test["tonal"]=round(X_test["tonal"],4)

In [135]:
# X_test = X_test.replace(np.nan, 0)

In [136]:
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline
sgd = SGDClassifier()
sgd = sgd.fit(X_train,y_train)
predicted = sgd.predict(X_test)

/Applications/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


In [144]:
from sklearn.metrics import precision_recall_fscore_support
p,r,f,s = precision_recall_fscore_support(predicted, y_test)


/Applications/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [145]:
p

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.07692308,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ])

In [146]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predicted))

0.0283333333333


In [147]:
# from sklearn.model_selection import cross_val_score
# >>> clf = svm.SVC(kernel='linear', C=1)
# >>> scores = cross_val_score(clf, iris.data, iris.target, cv=5)
# >>> scores  



from sklearn import svm
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1)
scores = cross_val_score(clf, TRAIN, labels, cv=10)
scores  


# from sklearn.model_selection import ShuffleSplit
# cv = ShuffleSplit(n_splits=3, test_size=0.3, random_state=0)
# cross_val_score(clf, TRAIN, labels, cv=cv)

array([ 0.03 ,  0.025,  0.015,  0.015,  0.02 ,  0.015,  0.015,  0.005,
        0.01 ,  0.015])

In [148]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.02 (+/- 0.01)


In [149]:
from sklearn import metrics
Mscores = cross_val_score(clf, TRAIN, labels, cv=10, scoring='accuracy')
Mscores  

array([ 0.03 ,  0.025,  0.015,  0.015,  0.02 ,  0.015,  0.015,  0.005,
        0.01 ,  0.015])

In [150]:
from sklearn.model_selection import ShuffleSplit
n_samples = TRAIN.shape[0]
cv1 = ShuffleSplit(n_splits=10, test_size=0.2, random_state=0)
cross_val_score(clf, TRAIN, labels, cv=cv1)
                                                    


array([ 0.0025,  0.005 ,  0.005 ,  0.005 ,  0.    ,  0.0025,  0.01  ,
        0.005 ,  0.0075,  0.    ])

In [100]:
from sklearn.model_selection import KFold

# kf = RepeatedKFold(n_splits=5, n_repeats=10, random_state=None) 
kf = KFold(n_splits=10)
kf.get_n_splits(TRAIN)
# for train_index, test_index in kf.split(TRAIN):
#     print("Test:", test_index)
# #     print(test_index)
# #     X_train, X_test = TRAIN[train_index], TRAIN[test_index] 
#     y_train, y_test = labels[train_index], labels[test_index]




# for train_index, test_index in kf.split(TRAIN):
#     for i in test_index:
#         print("TRAIN:", train_index, "TEST:", test_index)
#         X_train, X_test = TRAIN[train_index], TRAIN[i]
#         y_train, y_test = labels[train_index], labels[i]

TRAIN: [ 200  201  202 ..., 1997 1998 1999] TEST: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199]


KeyError: '[ 200  201  202 ..., 1997 1998 1999] not in index'